DROP TABLE IF EXISTS patents CASCADE;
DROP TABLE IF EXISTS staking_pools CASCADE;
DROP TABLE IF EXISTS projects CASCADE;
DROP TABLE IF EXISTS artists CASCADE;
DROP TABLE IF EXISTS funding_contracts CASCADE;