// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zauwonpsybhwcgmmzwxb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InphdXdvbnBzeWJod2NnbW16d3hiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk0ODIzOTUsImV4cCI6MjA2NTA1ODM5NX0.vRWlPnCFf6zaryTS0xGsV-xAtZs076HpZdjGZ3ZayMk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);